### ISSUE TITLE
Error when running picat via minizinc

### ISSUE THREAD

**Issue by ndangtt** [nfzhou/fzn_picat#2]
Hello,

May I ask for your help on the following issue please?

When running picat on some instances of the carpet-cutting problem (MiniZinc competition 2020), I encountered the following error message:
```
% solving(./tmp/mznfile24xPAx.fzn)
% loading ./tmp/mznfile24xPAx.fzn
% obj = 12154
solution received from solver:4.18-20:
objective = 12154';'
                 ^^^
Error: syntax error, unexpected identifier, expecting end of file
solns2out_base: could not parse solution
```

The command I used:
```
minizinc --solver picat -f problem.mzn inst.dzn 
```

I attach here the minizinc model and the instance I used. I tested picat on a few other optimisation problems and it was fine, so I suppose my minizinc setup was okay.

Thank you very much!

Nguyen
[inst-2-1403093695.dzn.txt](https://github.com/nfzhou/fzn_picat/files/7857842/inst-2-1403093695.dzn.txt)
[problem.mzn.txt](https://github.com/nfzhou/fzn_picat/files/7857844/problem.mzn.txt)

**Comment by hakank** [comment]
The problem is that Picat version 3.1.6 changed the behavior of `writeln/1` and now prints `';'` as a quoted character.

It should work if your change `writeln(';')` at line 360 to `println(';')`, i.e. this diff:

```
@@ -357,7 +357,7 @@ fzn_output([]) => println('----------').
 fzn_output([output_var(Ident,Type,Var)|L]) =>
     printf("%w = ",Ident),
     fzn_write(Type,Var),
-    writeln(';'),
+    println(';'),^M
     fzn_output(L).
 fzn_output([output_array(Ident,Ranges,ElmType,BPArr)|L]) =>
     length(Ranges) = Dim,

```
I've created a pull request for this (https://github.com/nfzhou/fzn_picat/pull/3).

**Comment by ndangtt** [comment]
Thank you so much for fixing it! I can confirm that it works now for my cases :)

**Comment by nfzhou** [comment]
Thank you for pointing that out. I have updated the file.

-NF
